/*----------------------------------------------------------------------
 *
 * Filename: TaintSummaryFile.cpp
 * Description:
 *
 * Date       Pgm  Comment
 * 18 Jan 26  jpb  Creation.
 *
 */
#include "TaintSummaryFile.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cctype>
#include <fstream>

namespace taint
{

//
// SummaryFileWriter Implementation
//

std::string SummaryFileWriter::indent (int level)
{
    return std::string (level * 2, ' ');
}

std::string SummaryFileWriter::layerToYaml (TaintLayer layer)
{
    switch (layer)
        {
        case TaintLayer::RAW:
            return "RAW";
        case TaintLayer::SYNTACTIC:
            return "SYNTACTIC";
        case TaintLayer::SEMANTIC:
            return "SEMANTIC";
        case TaintLayer::CONTEXTUAL:
            return "CONTEXTUAL";
        case TaintLayer::CLEAN:
            return "CLEAN";
        }
    return "UNKNOWN";
}

std::string SummaryFileWriter::directionToYaml (ParamDirection dir)
{
    switch (dir)
        {
        case ParamDirection::IN:
            return "IN";
        case ParamDirection::OUT:
            return "OUT";
        case ParamDirection::INOUT:
            return "INOUT";
        }
    return "IN";
}

std::string modStatusToYaml (ParamModStatus status)
{
    switch (status)
        {
        case ParamModStatus::UNKNOWN:
            return "UNKNOWN";
        case ParamModStatus::PASS_THROUGH:
            return "PASS_THROUGH";
        case ParamModStatus::MODIFIED:
            return "MODIFIED";
        }
    return "UNKNOWN";
}

bool SummaryFileWriter::write (const std::string &filename,
                          const std::vector<FunctionSummary> &summaries,
                          const std::string &sourceFile)
{
    std::ofstream out (filename);
    if (!out.is_open ())
        {
            llvm::errs () << "Error: Cannot open file for writing: " << filename
                          << "\n";
            return false;
        }

    out << "# Taint Summary File\n";
    out << "# Generated by taint-analyzer\n";
    out << "---\n";
    out << "version: 2\n"; // Version bump for provenance support
    out << "source_file: " << sourceFile << "\n";
    out << "functions:\n";

    for (const auto &func : summaries)
        {
            out << indent (1) << "- name: " << func.name << "\n";
            out << indent (2) << "qualified_name: " << func.qualifiedName
                << "\n";
            out << indent (2)
                << "return_layer: " << layerToYaml (func.returnLayer) << "\n";
            out << indent (2) << "return_inherits: "
                << (func.returnInherits ? "true" : "false") << "\n";
            out << indent (2)
                << "return_inherit_source: " << func.returnInheritSource
                << "\n";
            out << indent (2) << "is_taint_source: "
                << (func.isTaintSource ? "true" : "false") << "\n";
            out << indent (2)
                << "is_taint_sink: " << (func.isTaintSink ? "true" : "false")
                << "\n";
            out << indent (2)
                << "sink_requirement: " << layerToYaml (func.sinkRequirement)
                << "\n";

            if (!func.params.empty ())
                {
                    out << indent (2) << "params:\n";
                    for (const auto &param : func.params)
                        {
                            out << indent (3) << "- index: " << param.index
                                << "\n";
                            if (!param.name.empty ())
                                {
                                    out << indent (4) << "name: " << param.name
                                        << "\n";
                                }
                            out << indent (4) << "direction: "
                                << directionToYaml (param.direction) << "\n";
                            out << indent (4) << "required_layer: "
                                << layerToYaml (param.requiredLayer) << "\n";
                            out << indent (4) << "output_layer: "
                                << layerToYaml (param.outputLayer) << "\n";
                            out << indent (4) << "inherits_from_param: "
                                << (param.inheritsFromParam ? "true" : "false")
                                << "\n";
                            out << indent (4)
                                << "inherit_source: " << param.inheritSource
                                << "\n";
                            out << indent (4) << "mod_status: "
                                << modStatusToYaml (param.modStatus) << "\n";
                        }
                }

            // Write call sites if present (provenance data)
            if (!func.callSites.empty ())
                {
                    out << indent (2) << "call_sites:\n";
                    for (const auto &cs : func.callSites)
                        {
                            out << indent (3) << "- callee: " << cs.calleeName
                                << "\n";
                            out << indent (4) << "location: \"" << cs.location
                                << "\"\n";
                            if (!cs.bindings.empty ())
                                {
                                    out << indent (4) << "bindings:\n";
                                    for (const auto &b : cs.bindings)
                                        {
                                            out << indent (5)
                                                << "- arg_index: " << b.argIndex
                                                << "\n";
                                            out << indent (6)
                                                << "from_caller_param: "
                                                << (b.fromCallerParam ? "true"
                                                                      : "false")
                                                << "\n";
                                            if (b.fromCallerParam)
                                                {
                                                    out << indent (6)
                                                        << "caller_param_index:"
                                                           " "
                                                        << b.callerParamIndex
                                                        << "\n";
                                                    out << indent (6)
                                                        << "is_direct_pass_"
                                                           "through: "
                                                        << (b.isDirectPassThrough
                                                                ? "true"
                                                                : "false")
                                                        << "\n";
                                                }
                                            if (!b.sourceName.empty ())
                                                {
                                                    out << indent (6)
                                                        << "source_name: \""
                                                        << b.sourceName
                                                        << "\"\n";
                                                }
                                        }
                                }
                        }
                }
        }

    out << "...\n";
    out.close ();
    return true;
}

bool SummaryFileWriter::writeDatabase (const std::string &filename,
                                  const FunctionDatabase &db)
{
    // This would need access to the internal summaries map
    // For now, we write summaries per-file
    return false;
}

//
// SummaryFileReader Implementation
//

std::string SummaryFileReader::trim (const std::string &str)
{
    size_t start = str.find_first_not_of (" \t\n\r");
    if (start == std::string::npos)
        return "";
    size_t end = str.find_last_not_of (" \t\n\r");
    return str.substr (start, end - start + 1);
}

std::string SummaryFileReader::getValue (const std::string &line)
{
    size_t pos = line.find (':');
    if (pos == std::string::npos)
        return "";
    return trim (line.substr (pos + 1));
}

#if 0
bool
SummaryFileReader::startsWith (const std::string &str,
                               const std::string &prefix)
{
    std::string trimmed = trim (str);
    return trimmed.find (prefix) == 0;
}
#endif

TaintLayer
SummaryFileReader::parseLayer (const std::string &str)
{
    std::string s = trim (str);
    if (s == "RAW")
        return TaintLayer::RAW;
    if (s == "SYNTACTIC")
        return TaintLayer::SYNTACTIC;
    if (s == "SEMANTIC")
        return TaintLayer::SEMANTIC;
    if (s == "CONTEXTUAL")
        return TaintLayer::CONTEXTUAL;
    if (s == "CLEAN")
        return TaintLayer::CLEAN;
    return TaintLayer::RAW; // Default
}

ParamDirection
SummaryFileReader::parseDirection (const std::string &str)
{
    std::string s = trim (str);
    if (s == "IN")
        return ParamDirection::IN;
    if (s == "OUT")
        return ParamDirection::OUT;
    if (s == "INOUT")
        return ParamDirection::INOUT;
    return ParamDirection::IN; // Default
}

ParamModStatus
parseModStatus (const std::string &str)
{
    std::string s = str;
    // Trim
    size_t start = s.find_first_not_of (" \t\n\r");
    if (start != std::string::npos)
        {
            size_t end = s.find_last_not_of (" \t\n\r");
            s = s.substr (start, end - start + 1);
        }
    if (s == "PASS_THROUGH")
        return ParamModStatus::PASS_THROUGH;
    if (s == "MODIFIED")
        return ParamModStatus::MODIFIED;
    return ParamModStatus::UNKNOWN;
}

bool
SummaryFileReader::read (const std::string &filename,
                         std::vector<FunctionSummary> &summaries)
{
    std::ifstream in (filename);
    if (!in.is_open ())
        {
            llvm::errs () << "Error: Cannot open file for reading: " << filename
                          << "\n";
            return false;
        }

    summaries.clear ();

    std::string line;
    FunctionSummary currentFunc;
    ParamSummary currentParam;
    bool inFunction = false;
    bool inParams = false;
    bool inParam = false;

    enum class State
    {
        TOP,
        FUNCTIONS,
        FUNCTION,
        PARAMS,
        PARAM
    };
    State state = State::TOP;

    while (std::getline (in, line))
        {
            std::string trimmed = trim (line);

            // Skip comments and empty lines
            if (trimmed.empty () || trimmed[0] == '#' || trimmed == "---"
                || trimmed == "...")
                {
                    continue;
                }

            if (trimmed.starts_with("version:"))
                {
                    // Version check could go here
                    continue;
                }

            if (trimmed.starts_with("source_file:"))
                {
                    // Could store source file
                    continue;
                }

            if (trimmed.starts_with("functions:"))
                {
                    state = State::FUNCTIONS;
                    continue;
                }

            if (state == State::FUNCTIONS || state == State::FUNCTION
                || state == State::PARAMS || state == State::PARAM)
                {

                    // New function entry
                    if (trimmed.find ("- name:") == 0)
                        {
                            // Save previous function if exists
                            if (inFunction)
                                summaries.push_back (currentFunc);

                            // Start new function
                            currentFunc = FunctionSummary ();
                            currentFunc.name = getValue (trimmed);
                            inFunction = true;
                            inParams = false;
                            inParam = false;
                            state = State::FUNCTION;
                            continue;
                        }

                    // New param entry
                    if (trimmed.find ("- index:") == 0)
                        {
                            // Save previous param if exists
                            if (inParam)
                                {
                                    currentFunc.params.push_back (currentParam);
                                }

                            // Start new param
                            currentParam = ParamSummary ();
                            currentParam.index = std::stoi (getValue (trimmed));
                            inParam = true;
                            state = State::PARAM;
                            continue;
                        }

                    // Function fields
                    if (state == State::FUNCTION && !inParams)
                        {
                            if (trimmed.starts_with("qualified_name:"))
                                {
                                    currentFunc.qualifiedName
                                        = getValue (trimmed);
                                }
                            else if (trimmed.starts_with("return_layer:"))
                                {
                                    currentFunc.returnLayer
                                        = parseLayer (getValue (trimmed));
                                }
                            else if (trimmed.starts_with("return_inherits:"))
                                {
                                    currentFunc.returnInherits
                                        = (getValue (trimmed) == "true");
                                }
                            else if (trimmed.starts_with("return_inherit_source:"))
                                {
                                    currentFunc.returnInheritSource
                                        = std::stoi (getValue (trimmed));
                                }
                            else if (trimmed.starts_with("is_taint_source:"))
                                {
                                    currentFunc.isTaintSource
                                        = (getValue (trimmed) == "true");
                                }
                            else if (trimmed.starts_with("is_taint_sink:"))
                                {
                                    currentFunc.isTaintSink
                                        = (getValue (trimmed) == "true");
                                }
                            else if (trimmed.starts_with("sink_requirement:"))
                                {
                                    currentFunc.sinkRequirement
                                        = parseLayer (getValue (trimmed));
                                }
                            else if (trimmed.starts_with("params:"))
                                {
                                    inParams = true;
                                    state = State::PARAMS;
                                }
                        }

                    // Param fields
                    if (state == State::PARAM && inParam)
                        {
                            if (trimmed.starts_with("name:"))
                                {
                                    currentParam.name = getValue (trimmed);
                                }
                            else if (trimmed.starts_with("direction:"))
                                {
                                    currentParam.direction
                                        = parseDirection (getValue (trimmed));
                                }
                            else if (trimmed.starts_with("required_layer:"))
                                {
                                    currentParam.requiredLayer
                                        = parseLayer (getValue (trimmed));
                                }
                            else if (trimmed.starts_with("output_layer:"))
                                {
                                    currentParam.outputLayer
                                        = parseLayer (getValue (trimmed));
                                }
                            else if (trimmed.starts_with("inherits_from_param:"))
                                {
                                    currentParam.inheritsFromParam
                                        = (getValue (trimmed) == "true");
                                }
                            else if (trimmed.starts_with("inherit_source:"))
                                {
                                    currentParam.inheritSource
                                        = std::stoi (getValue (trimmed));
                                }
                            else if (trimmed.starts_with("mod_status:"))
                                {
                                    currentParam.modStatus
                                        = parseModStatus (getValue (trimmed));
                                }
                        }
                }
        }

    // Save last function and param
    if (inParam)
        {
            currentFunc.params.push_back (currentParam);
        }
    if (inFunction)
        {
            // Rebuild the pass-through/modified sets from params
            currentFunc.rebuildParamSets ();
            summaries.push_back (currentFunc);
        }

    in.close ();
    return true;
}

bool
SummaryFileReader::loadIntoDatabase (const std::string &filename,
                                     FunctionDatabase &db)
{
    std::vector<FunctionSummary> summaries;
    if (!read (filename, summaries))
        {
            return false;
        }

    for (const auto &summary : summaries)
        {
            db.addSummary (summary);
        }

    llvm::errs () << "Loaded " << summaries.size () << " summaries from "
                  << filename << "\n";
    return true;
}

bool
SummaryFileReader::loadDirectory (const std::string &directory,
                                  FunctionDatabase &db)
{
    namespace fs = std::filesystem;

    if (!fs::exists (directory) || !fs::is_directory (directory))
        {
            return false;
        }

    int count = 0;
    for (const auto &entry : fs::directory_iterator (directory))
        {
            if (entry.path ().extension () == ".taint")
                {
                    if (loadIntoDatabase (entry.path ().string (), db))
                        {
                            count++;
                        }
                }
        }

    llvm::errs () << "Loaded summaries from " << count << " files in "
                  << directory << "\n";
    return count > 0;
}

//
// SummaryManager Implementation
//

SummaryManager::SummaryManager (FunctionDatabase &db) : db_ (db) {}

std::string
SummaryManager::getSummaryPath (const std::string &sourceFile)
{
    namespace fs = std::filesystem;

    fs::path source (sourceFile);
    std::string basename = source.stem ().string ();
    return basename + ".taint";
}

bool
SummaryManager::saveSummaries (const std::string &sourceFile,
                               const std::vector<FunctionSummary> &summaries)
{
    namespace fs = std::filesystem;

    // Create summary directory if it doesn't exist
    if (!fs::exists (summaryDir_))
        {
            fs::create_directories (summaryDir_);
        }

    std::string summaryFile = summaryDir_ + "/" + getSummaryPath (sourceFile);
    return SummaryFileWriter::write (summaryFile, summaries, sourceFile);
}

bool
SummaryManager::loadSummaries (const std::string &directory)
{
    return SummaryFileReader::loadDirectory (directory, db_);
}

} // namespace taint
